groups:
  - name: backend_alerts
    rules:
      - alert: BackendHighMemory
        expr: process_virtual_memory_bytes > 100000000 #100Mo
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Consommation mémoire critique sur le backend"