import z from 'zod';
import {
  MESSAGE_CONTENT_MAX_LENGTH,
  USER_BIOGRAPHY_MAX_LENGTH,
  USER_BIOGRAPHY_MIN_LENGTH,
  USER_EMAIL_MAX_LENGTH,
  USER_EMAIL_MIN_LENGTH,
  USER_EMAIL_REGEX,
  USER_NAME_MAX_LENGTH,
  USER_NAME_MIN_LENGTH,
  USER_PASSWORD_MAX_LENGTH,
  USER_PASSWORD_MIN_LENGTH,
  USER_USERNAME_MAX_LENGTH,
  USER_USERNAME_MIN_LENGTH,
  USER_USERNAME_REGEX,
} from '../constants/constants';

// User
export const ZOD_USER_USERNAME = z
  .string()
  .min(USER_USERNAME_MIN_LENGTH)
  .max(USER_USERNAME_MAX_LENGTH)
  .regex(USER_USERNAME_REGEX);
export const ZOD_USER_PASSWORD = z
  .string()
  .min(USER_PASSWORD_MIN_LENGTH)
  .max(USER_PASSWORD_MAX_LENGTH)
  .describe('Test');
export const ZOD_USER_EMAIL = z
  .string()
  .min(USER_EMAIL_MIN_LENGTH)
  .max(USER_EMAIL_MAX_LENGTH)
  .regex(USER_EMAIL_REGEX);
export const ZOD_USER_NAME = z
  .string()
  .min(USER_NAME_MIN_LENGTH)
  .max(USER_NAME_MAX_LENGTH);
export const ZOD_USER_BIOGRAPHY = z
  .string()
  .min(USER_BIOGRAPHY_MIN_LENGTH)
  .max(USER_BIOGRAPHY_MAX_LENGTH);

// Message
export const ZOD_MESSAGE_CONTENT = z.string().max(MESSAGE_CONTENT_MAX_LENGTH);
