volumes:
  database:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ./data/database

services:
  database:
    container_name: database
    networks:
      - unicord
    image: mariadb:12
    env_file: .env
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    networks:
      - unicord
    depends_on:
      - frontend
      - backend
    build:
      context: ./nginx
      args:
        FRONTEND_DOMAIN: ${FRONTEND_DOMAIN}
        BACKEND_DOMAIN: ${BACKEND_DOMAIN}
    env_file: .env
    restart: unless-stopped
    ports:
      - "443:443"

  backend:
    container_name: backend
    networks:
      - unicord
    volumes:
      - ./data/uploads:/app/uploads
    depends_on:
      - database
    build: ./backend
    env_file: .env
    restart: unless-stopped
    expose:
      - "3000"

  frontend:
    container_name: frontend
    networks:
      - unicord
    depends_on:
      - backend
    build: ./frontend
    env_file: .env
    restart: unless-stopped
    expose:
      - "3001"

networks:
  unicord:
    name: unicord
    driver: bridge
