volumes:
  database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./data/database

services:
  database:
    container_name: database
    networks:
    - unicord
    build: ./database
    env_file: .env
    volumes:
    - database:/var/lib/mysql
    restart: unless-stopped
    expose:
    - "3306"

  backend:
    container_name: backend
    networks:
    - unicord
    depends_on:
    - database
    build: ./backend
    env_file: .env
    restart: unless-stopped
    ports:
    - "3000:3000" # TMP (NGINX)

  frontend:
    container_name: frontend
    networks:
    - unicord
    depends_on:
    - backend
    build: ./frontend
    env_file: .env
    restart: unless-stopped
    ports:
    - "3001:3001" # TMP (NGINX)

networks:
  unicord:
    name: unicord
    driver: bridge